name: GA0_Q_13

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  test:
    steps:
      - name: 24f2006495@ds.study.iitm.ac.in
        run: echo "Hello, world!"
