name: GA0 Question 13

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  test:
    steps:
      - name: 24f2006495@ds.study.iitm.ac.in
        run: echo "Hello, world!"
